version: "3.1"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - "8080:80"
    command: 'bash -c "apt-get update -y && apt-get install -y apache2-utils && apt-get install apache2-utils && cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && htpasswd -c -b /etc/nginx/auth.htpasswd agency admin && nginx -g ''daemon off;''"'
  node:
    image: node:10.14
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
